### PR TITLE
Build error fix

### PR DESCRIPTION
**Pull request by thomassth**
Besides syncing the branch with other commits, this PR fixes the build errors caused by `d3-contour` import.

### CODE REVIEW

**Comment by NewJerseyStyle** [comment]
No description provided. Review cannot proceed.

**Comment by NewJerseyStyle** [comment]
Unable to verify the fix on my side.
```
 > [file-server client-report 5/7] RUN npm ci --production=false:
6.506 npm warn config production Use `--omit=dev` instead.
763.6 npm warn deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
2294.6 npm warn deprecated node-uuid@1.4.8: Use uuid module instead
2326.6 npm warn deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
2330.6 npm warn deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2333.9 npm warn deprecated request@2.65.0: request has been deprecated, see https://github.com/request/request/issues/3142
2405.9 npm warn deprecated har-validator@2.0.6: this library is no longer supported
2632.9 npm warn deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2634.1 npm warn deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
2685.2 npm warn deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
3865.1 npm notice
3865.1 npm notice New minor version of npm available! 10.7.0 -> 10.8.3
3865.1 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
3865.1 npm notice To update run: npm install -g npm@10.8.3
3865.1 npm notice
3865.9 npm error code ECONNRESET
3865.9 npm error errno ECONNRESET
3865.9 npm error network request to https://registry.npmjs.org/@webassemblyjs/helper-numbers/-/helper-numbers-1.11.6.tgz failed, reason: Client network socket disconnected before secure TLS connection was established
3865.9 npm error network This is a problem related to network connectivity.
3865.9 npm error network In most cases you are behind a proxy or have bad network settings.
3865.9 npm error network
3865.9 npm error network If you are behind a proxy, please make sure that the
3865.9 npm error network 'proxy' config is set properly.  See: 'npm help config'
3866.4 
3866.4 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-09-12T02_38_27_090Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm ci --production=false" did not complete successfully: exit code: 1
```

**Comment by NewJerseyStyle** [comment]
Now checkout to `edge` branch to test my environment

**Comment by NewJerseyStyle** [comment]
My environment cannot build and run any of the polis version. Waiting for Jamie to verify the fix.

**Comment by jamiepantling** [comment]
I do seem to be able to build with this fix by using:
`docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build`

**Comment by NewJerseyStyle** [comment]
I assume `Bad Gateway error` is network issue caused by other reason and this pull request aimed to fix a build error. Since Jamie was able to build, I consider this fix is valid.

**Pull request merged**
