### PR TITLE
Fixes issue with docker build failing due to makefile typo

### LINKED ISSUE #33: Makefile is broken on osx with zsh
**Expected behavior**:
For `make build` on edge branch to build successfully

**Actual behavior**:
I get this error:

```
$ make build
ENV_FILE=.env
POSTGRES_DOCKER= true
TAG= dev
docker compose -f docker-compose.yml -f docker-compose.dev.yml --profile postgres --env-file .env build
[+] Building 0.0s (0/0)                                                                                                                                                                       docker:colima
invalid tag "docker.io/compdem/polis-postgres:\tdev": invalid reference format
make: *** [build] Error 17
```

**To Reproduce**:
Git clone and run `make build` or `make echo_vars`

Note the tabs "\t" in the output, and the whitespace in the vars

**Screenshots**:
Screenshot 2024-10-17 at 2 18 20 PM

**Device information**:
Current environment:
- OSX Sonoma 14.5
- zsh 5.9 (x86_64-apple-darwin23.0)
- **colima** version 0.7.5 (alternative docker-compat container runtime)
  - this is the only "weird" thing, but I isolated a fix in the makefile environmen
- Docker version 27.2.1, build 9e34c9bb39
- Docker Compose version 2.29.2
- GNU Make 3.81

**Additional context**:
None

## Solution

I've found a fix that I will share shortly. Basically, issue involves make format, the `define` method, and whitespace in a place that make doesn't like it :)

### PR DESCRIPTION
**Pull request by patcon**
Resolves CivicTechTO/polis#33

### CODE REVIEW

**Review by NewJerseyStyle — APPROVED** [review]
Resolved spaces strikes! 🎉

**Comment by patcon** [comment]
Ah thanks David, but this got merged upstream, so will likely need to be reverted and force-pushed here, so edge stays in sync with upstream as intended...! Sorry, should've prob left it in draft :)

**Comment by patcon** [comment]
Sorry, I thought that I'd protected our new edge branch so it could only be sync'd from upstream, but I clearly misunderstood that feature

**Comment by NewJerseyStyle** [comment]
Umm... I am trying to understand:
* So the edge also serve as a branch to push to the upstream?
* The edge records the latest change in our repo will cause conflict?

**Comment by patcon** [comment]
> - So the edge also serve as a branch to push to the upstream? :x: no, just to pull into our repo, and rebase/merge/whatever as needed to track upstream cleanly
> - The edge records the latest change in our repo will cause conflict? ✅ 

Or if not guaranteed conflict, then certainly confusion. Mundane sorts of things [like this](https://github.com/compdemocracy/polis/pull/1821#issuecomment-2420355569) are pretty much certain, because anyone working locally can't easily tell _our_ `edge` from _upstream_ `edge` (most local workflows would have a remote set for the compdem repo and another for civictechto repo, both configured in the same repo).

For example:

```sh
$ git clone https://github.com/civictechto/polis.git && cd polis
$ git remote add upstream https://github.com/compdemocracy/polis.git
$ git checkout edge # we're on the civictechto edge (with extra commits)

  # now we want to pull upstream and merge it into something else
  # but need to do weird git-fu to set local tracking branch name to something diff than remote branch.
  # if someone doesn't know how to do wierd git-fu, things like this happen:

$ git pull upstream main # fails
$ git pull upstream main --rebase # succeeds but rebases out changes onto theirs, and breaks the history, requiring a force-push

  # or when making a PR branch locally

$ git checkout -b my-new-feature # creates a new branch that looks like it's off of upstream edge, but then

  # when done working and try to submit PR, all the commits from our `edge` get accidentally sent as well.
  # This is a really common error in open source contribution, then we side-step if we don't use `edge` in our downstream flow as well
  # etc etc etc
```

We would normally rebase or merge in the upstream changes by pulling `edge`, then merging it into ours locally. Working on a downstream branch that we don't intend to push (or keep in sync) with their branch of the same name, is not something I've seen chosen in collaborative projects 🙏

**Pull request merged**
