### PR TITLE
Merge `storybook-prep` improvements

### PR DESCRIPTION
**Pull request by thomassth**
Merging cleanup efforts from `storybook-prep` branch
- Radium calls updated
- Connect calls updated

### CODE REVIEW

**Comment by patcon** [comment]
I have no opinion on whether this goes into `edge-civictechto` (I hope to upstream it later), but pls ensure it doesn't get deleted -- it's intended to be a long-lived branch, not a feature branch :)

**Comment by NewJerseyStyle** [comment]
Any relationship with #100 ? @yshng any idea?

**Comment by thomassth** [comment]
Probably superceded by #93, close after that's done

**Comment by patcon** [comment]
To explain: this branch only existed to be the minimal changeset upstream needed to get storybook working. it's a tracking branch, and wasn't expected to be merged/deleted locally until the changes were no longer needed upstream

**Comment by patcon** [comment]
The polis-storybook repo should be relying on this still. This PR is a prob a bit confusing in its existence, bc the only diff that matters for my purposes is against upstream `edge`: https://github.com/compdemocracy/polis/compare/edge...CivicTechTO:polis:storybook-prep

I would recommend closing this PR and maybe protecting the branch (it's too bad that it's not easy to add notes to branches about why they exist)

**Comment by NewJerseyStyle** [comment]
Every time I saw the PR title and the message at the top by @thomassth I get confused if any action should take 🤣

**Comment by patcon** [comment]
Solved? Pls re-open if I've misunderstood :)

**Pull request closed without merging**
